services:
  portfolio:
    build: .
    container_name: my-portfolio
    restart: always
    ports:
      - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`elmountahi.dev`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio-http.rule=Host(`elmountahi.dev`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    environment:
      - NODE_ENV=production
    networks:
      - web

networks:
  web:
    external: true
